name: file_sharing
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # UI packages
  cupertino_icons: ^1.0.6
  flutter_svg: 2.0.10+1
  # routing
  auto_route: ^9.1.0
  # app local data
  shared_preferences: ^2.3.1
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  date_picker_timeline: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linters
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  # for building and generating dart code according to the generators.
  # use it with "dart run build_runner (build or watch)".
  build_runner: ^2.4.11
  # generators
  auto_route_generator: ^9.0.0
  riverpod_generator: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
